{% set name = "analysta" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ..

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - pandas >=1.4
    - typer >=0.9.0
    - jinja2 >=3.0

test:
  imports:
    - analysta
  commands:
    - analysta --help
    - analysta version

about:
  home: https://github.com/dunkel000/analysta
  summary: DataFrame Toolkit for Analysts
  description: |
    A Python library for comparing pandas DataFrames using primary keys,
    tolerances, and audit-friendly diffs. Easily detect mismatches,
    missing rows, and cell-level changes between two datasets.
    
    Features:
    - Key-based row comparison
    - Tolerant numeric diffs (absolute & relative)
    - CLI for terminal-based workflows
    - HTML reporting for easy sharing
    - CSV and Excel import/export helpers
    - Data quality audit helpers
  dev_url: https://github.com/dunkel000/analysta
  license: MIT
  license_file: LICENSE.txt
